let words = [
  ["conflict", "cart", "facsimile"],
  ["submitter", "athlete", "fratricide"],
  ["frenzy", "finish", "dory"],
  ["inlay", "encouragement", "dagger"],
  ["media", "somersault", "diabetes"],
  ["cabana", "kingdom", "spread"],
  ["catalogue", "jackal", "stepping-stone"],
  ["portion", "noodles", "facility"],
  ["alias", "maggot", "sherry"],
  ["religion", "guinea", "cob"],
  ["server", "change", "obesity"],
  ["grandma", "record", "deed"],
  ["parallelogram", "churn", "isogloss"],
  ["deep", "revitalization", "mound"],
  ["contrast", "project", "relaxation"],
  ["cheese", "earthworm", "raiment"],
  ["abdomen", "flavor", "ear"],
  ["equipment", "haircut", "packet"],
  ["symmetry", "chicken", "shampoo"],
  ["citron", "cesspool", "administrator"],
  ["angiosperm", "cicada", "socialism"],
  ["pine", "possession", "seizure"],
  ["mRNA", "sneaker", "chub"],
  ["mambo", "chemistry", "curl"],
  ["poisoning", "margin", "colonisation"],
  ["expense", "amount", "gemsbok"],
  ["location", "shred", "livestock"],
  ["ankle", "radiosonde", "bathroom"],
  ["amazon", "derrick", "mile"],
  ["orator", "afoul", "gasoline"],
  ["ballpark", "bar", "baggage"],
  ["presume", "proliferation", "ban"],
  ["legitimacy", "prevalence", "affinity"],
  ["appropriation", "entry", "euphonium"],
  ["survival", "shop", "incentive"],
  ["runway", "offence", "gosling"],
  ["drum", "retention", "barrage"],
  ["delight", "lashes", "emu"],
  ["respect", "measurement", "nationality"],
  ["signup", "psychologist", "bayou"],
  ["omelet", "chalice", "enforcement"],
  ["controversy", "stimulus", "anticipation"],
  ["fortnight", "sundae", "gelding"],
  ["pitch", "shaw", "probe"],
  ["crest", "batter", "desire"],
  ["girl", "heron", "elimination"],
  ["footprint", "expertise", "dirndl"],
  ["fool", "outrun", "hunter"],
  ["cytoplasm", "film", "mileage"],
  ["keystone", "rust", "ginseng"],
  ["alfalfa", "nucleotide", "beast"],
  ["arrow", "salt", "shed"],
  ["craw", "stalk", "beanstalk"],
  ["pistol", "elbow", "thorn"],
  ["handsaw", "patent", "processing"],
  ["raspberry", "lion", "committee"],
  ["rhythm", "smile", "foreigner"],
  ["coffee", "queen", "resistance"],
  ["ink", "echidna", "excess"],
  ["constitution", "sanctuary", "artist"],
  ["radish", "lark", "criminal"],
  ["glider", "armour", "dust storm"],
  ["quilt", "penicillin", "derivation"],
  ["spelling", "merchandise", "clan"],
  ["mussel", "lilac", "income"],
  ["estuary", "bachelor", "breakfast"],
  ["narrative", "inequality", "hops"],
  ["penis", "hospice", "electronics"],
  ["elderberry", "serval", "contrary"],
  ["equinox", "spawn", "guitarist"],
  ["suitcase", "legend", "flute"],
  ["sponsorship", "generation", "granddaughter"],
  ["crotch", "metaphor", "pear"],
  ["haven", "highland", "patrolling"],
  ["fog", "feeding", "singer"],
  ["middleman", "silica", "terrarium"],
  ["habitat", "country", "mansion"],
  ["floodplain", "pansy", "hassock"],
  ["stench", "request", "chairlift"],
  ["leaver", "pneumonia", "succotash"],
  ["ruling", "initial", "click"],
  ["burning", "molecule", "saddle"],
  ["cue", "morbid", "nature"],
  ["sunbonnet", "swath", "sculpting"],
  ["airspace", "furniture", "carotene"],
  ["stitch", "condor", "mirror"],
  ["silicon", "amenity", "other"],
  ["sunrise", "sigh", "motor"],
  ["headlight", "bureau", "reorganisation"],
  ["middle", "force", "taro"],
  ["skating", "reactant", "semiconductor"],
  ["armchair", "dialogue", "census"],
  ["puppy", "cutlet", "strobe"],
  ["gelatin", "circuit", "polo"],
  ["textbook", "supplier", "porthole"],
  ["milk", "permafrost", "minute"],
  ["dad", "extremist", "software"],
  ["joy", "chord", "curry"],
  ["element", "court", "keyboarding"],
  ["sideburns", "regard", "coevolution"],
  ["picnic", "screenwriting", "log"],
  ["ascend", "maybe", "baggy"],
  ["chaos", "consequence", "chafe"],
  ["hell", "dolman", "sign"],
  ["glance", "cartridge", "candy"],
  ["occasion", "money", "mineral"],
  ["patron", "major", "entree"],
  ["spike", "angel", "chem"],
  ["piece", "redirect", "landing"],
  ["dream", "devastation", "gauntlet"],
  ["bankbook", "obsession", "camera"],
  ["blush", "lament", "ranger"],
  ["strike", "boot", "stud"],
  ["stir-fry", "sensibility", "documentary"],
  ["tab", "cash", "consignment"],
  ["bracelet", "preoccupation", "baobab"],
  ["college", "thermals", "schoolhouse"],
  ["assurance", "talent", "bellows"],
  ["company", "call", "caboose"],
  ["tape", "quotation", "carload"],
  ["testing", "grandchild", "incident"],
  ["benefit", "elicit", "rainmaker"],
  ["substance", "arm", "minority"],
  ["mineshaft", "broadcast", "netball"],
  ["sequence", "excursion", "skullduggery"],
  ["methodology", "misreading", "member"],
  ["shorts", "diesel", "example"],
  ["bugle", "graft", "destiny"],
  ["beef", "brother", "lumberman"],
  ["distortion", "destroyer", "barbiturate"],
  ["cotton", "nightlight", "effort"],
  ["hyena", "heterosexual", "productivity"],
  ["sanctity", "ephemeris", "kick"],
  ["gator", "funeral", "disgust"],
  ["lending", "calcification", "hide"],
  ["pendant", "makeup", "police"],
  ["suite", "absence", "mall"],
  ["louse", "flick", "frock"],
  ["outrage", "misplacement", "ripple"],
  ["godfather", "prosecutor", "obligation"],
  ["step-brother", "fear", "bean"],
  ["subconscious", "implication", "shower"],
  ["rostrum", "cyst", "gown"],
  ["design", "job", "geranium"],
  ["beanie", "attenuation", "colonial"],
  ["foal", "bargain", "sabre"],
  ["pizza", "aluminium", "bootee"],
  ["area", "capability", "cruelty"],
  ["amazement", "panties", "thing"],
  ["acoustics", "acquaintance", "tea"],
  ["egghead", "chairperson", "grenade"],
  ["infinite", "hurdle", "scarification"],
  ["importance", "kiosk", "cucumber"],
  ["fortress", "reject", "drunk"],
  ["director", "monitoring", "pollution"],
  ["armament", "amnesty", "empowerment"],
  ["lemur", "fee", "exhaust"],
  ["distance", "shadowbox", "mouth"],
  ["mankind", "linkage", "barn"],
  ["glutamate", "messy", "genetics"],
  ["larva", "borrowing", "payoff"],
  ["consulate", "sir", "ceremony"],
  ["keyboard", "limestone", "gloom"],
  ["monastery", "spaghetti", "recorder"],
  ["attachment", "conductor", "parking"],
  ["routine", "battalion", "shoot"],
  ["incubation", "burden", "networking"],
  ["injunction", "app", "interior"],
  ["demon", "requirement", "hydrolyse"],
  ["banana", "plain", "kiwi"],
  ["museum", "tech", "episode"],
  ["bracket", "secretary", "interest"],
  ["avenue", "pleat", "macadamia"],
  ["paramedic", "gunpowder", "cinnamon"],
  ["solidity", "bestseller", "miss"],
  ["stage", "surrounds", "anniversary"],
  ["pimple", "loggia", "boudoir"],
  ["salmon", "notation", "detention"],
  ["badge", "oat", "tailbud"],
  ["aftermath", "envelope", "marketer"],
  ["clarity", "independence", "barium"],
  ["curler", "manifestation", "presence"],
  ["pick", "pray", "outhouse"],
  ["robotics", "childbirth", "framework"],
  ["officer", "reamer", "fireman"],
  ["fusarium", "pumpkinseed", "flanker"],
  ["holiday", "anywhere", "grain"],
  ["behest", "quality", "beginner"],
  ["throne", "sediment", "charger"],
  ["goose", "comeback", "check"],
  ["coin", "relay", "relish"],
  ["smolt", "sickness", "reluctance"],
  ["opera", "sorghum", "algorithm"],
  ["armpit", "psychiatrist", "reduction"],
  ["nectar", "bird", "pagoda"],
  ["decrease", "thong", "gravity"],
  ["cook", "multimedia", "shout"],
  ["lender", "gherkin", "collard"],
  ["postbox", "thaw", "compliance"],
  ["pause", "tambour", "affiliate"],
  ["rhinoceros", "spear", "flatboat"],
  ["nonsense", "help", "minibus"],
  ["arrest", "sow", "historian"],
  ["id", "sourwood", "liar"],
  ["post", "sociology", "crown"],
  ["path", "psychology", "ball"],
  ["net", "e-reader", "bowling"],
  ["negligee", "hepatitis", "pad"],
  ["rheumatism", "flicker", "nick"],
  ["entertainment", "parsnip", "interchange"],
  ["formula", "aglet", "swimsuit"],
  ["alto", "push", "strudel"],
  ["meatball", "hut", "needle"],
  ["maiden", "print", "epoxy"],
  ["cottage", "scow", "intentionality"],
  ["princess", "sky", "know-how"],
  ["girlfriend", "respite", "high"],
  ["suburb", "conviction", "drawbridge"],
  ["lunch", "instrumentalist", "drag"],
  ["plywood", "height", "goodwill"],
  ["cap", "listing", "lizard"],
  ["ecclesia", "edger", "butter"],
  ["tectonics", "resort", "sailing"],
  ["judgment", "lynx", "brief"],
  ["telescreen", "proprietor", "modernity"],
  ["clam", "sepal", "muffin"],
  ["list", "buying", "pomegranate"],
  ["percent", "biopsy", "shipping"],
  ["pupa", "pannier", "brown"],
  ["glucose", "mole", "notion"],
  ["self-esteem", "kebab", "oxford"],
  ["bull", "drudgery", "cost"],
  ["impress", "cookbook", "pastoralist"],
  ["certification", "hypochondria", "biscuit"],
  ["complicity", "disposition", "theft"],
  ["felony", "convection", "down"],
  ["stake", "prohibition", "tam-o'-shanter"],
  ["possibility", "rescue", "frigate"],
  ["phase", "journalist", "eddy"],
  ["download", "embarrassment", "overexertion"],
  ["proof-reader", "concentration", "jaguar"],
  ["congo", "savage", "intention"],
  ["grand", "bakeware", "aquarium"],
  ["smock", "sister-in-law", "mainstream"],
  ["machine", "confidentiality", "scrip"],
  ["monasticism", "tank-top", "blank"],
  ["dibble", "paint", "diplomacy"],
  ["payment", "continuity", "sanction"],
  ["romaine", "kingfish", "shoehorn"],
  ["anguish", "latte", "analysis"],
  ["divide", "fish", "bay"],
  ["fav", "poet", "generosity"],
  ["photodiode", "stupidity", "nanoparticle"],
  ["institute", "galley", "harmonize"],
  ["corporatism", "restructuring", "pat"],
  ["potty", "fallacy", "patriot"],
  ["sophomore", "commander", "pursuit"],
  ["evening", "cousin", "suspect"],
  ["planning", "porter", "isolation"],
  ["sequel", "eviction", "birdbath"],
  ["plant", "cannon", "ascent"],
  ["elf", "ivory", "dipstick"],
  ["dredger", "hutch", "configuration"],
  ["reaction", "guideline", "nylon"],
  ["anise", "control", "spandex"],
  ["quantity", "statistic", "sword"],
  ["revelation", "horde", "notice"],
  ["begonia", "man", "headquarters"],
  ["seed", "beancurd", "bomber"],
  ["meal", "crinoline", "pub"],
  ["latter", "pepper", "harald"],
  ["stop", "curiosity", "spiderling"],
  ["piracy", "music-box", "carter"],
  ["gyro", "roster", "brassiere"],
  ["doll", "forestry", "celsius"],
  ["predecessor", "freelance", "hall"],
  ["moccasins", "bedroom", "concept"],
  ["disadvantage", "cream", "oldie"],
  ["dancer", "apricot", "strand"],
  ["stinger", "freedom", "godmother"],
  ["gumshoe", "bike", "cleft"],
  ["civilisation", "funding", "reflection"],
  ["dig", "cone", "adrenaline"],
  ["icicle", "dryer", "tapioca"],
  ["poison", "millennium", "specification"],
  ["casement", "logo", "pumpkin"],
  ["godparent", "scaffold", "alcove"],
  ["picket", "edge", "fishing"],
  ["lip", "penalty", "larder"],
  ["diagnosis", "pew", "contrail"],
  ["tandem", "lighting", "gnat"],
  ["layout", "county", "dhow"],
  ["credit", "attacker", "cloud"],
  ["chives", "hardship", "fig"],
  ["ikebana", "prisoner", "manhunt"],
  ["mood", "stretch", "armrest"],
  ["calf", "terrorism", "borrower"],
  ["kumquat", "littleneck", "ferry"],
  ["plagiarism", "overheard", "breath"],
  ["lamb", "temporary", "swimming"],
  ["dramaturge", "misfit", "speaker"],
  ["surround", "pension", "faucet"],
  ["fingernail", "dwarf", "lambkin"],
  ["bassinet", "crash", "marriage"],
  ["ethernet", "efficiency", "coincidence"],
  ["preparation", "rivulet", "mop"],
  ["comics", "fang", "spur"],
  ["flume", "laundry", "curd"],
  ["stimulation", "leather", "belly"],
  ["retouching", "bookmark", "regionalism"],
  ["criticism", "march", "loop"],
  ["meeting", "aide", "acquisition"],
  ["cinder", "spring", "crisis"],
  ["tax", "disclosure", "riot"],
  ["background", "scratch", "joey"],
  ["snowboarding", "layer", "district"],
  ["squash", "fabric", "gap"],
  ["take-out", "spork", "good"],
  ["lanai", "oregano", "authorization"],
  ["planet", "milkshake", "capon"],
  ["iron", "hedgehog", "legal"],
  ["fledgling", "foot", "caper"],
  ["swell", "sunday", "heyday"],
  ["fishmonger", "teen", "carabao"],
  ["sonata", "certificate", "lettuce"],
  ["sake", "revolution", "repository"],
  ["page", "mustache", "city"],
  ["taste", "bow", "prospect"],
  ["tan", "resident", "tensor"],
  ["ophthalmologist", "packaging", "sailor"],
  ["mammoth", "courage", "selection"],
  ["intensity", "deviation", "sauerkraut"],
  ["expansion", "portrait", "suspenders"],
  ["minor", "hatchet", "spit"],
  ["cock", "sensitive", "ramie"],
  ["cricketer", "contact lens", "astrakhan"],
  ["corruption", "ex-husband", "chateau"],
  ["brisket", "mister", "ape"],
  ["inn", "fitness", "tenement"],
  ["roof", "run", "binoculars"],
  ["honeybee", "eagle", "pronunciation"],
  ["chapel", "choice", "faithful"],
  ["loafer", "bootie", "play"],
  ["cacao", "acrylic", "kilt"],
  ["finisher", "obedience", "consonant"],
  ["daybed", "association", "satellite"],
  ["soot", "cohort", "softdrink"],
  ["blinker", "garage", "blast"],
  ["network", "mycoplasma", "obi"],
  ["bee", "hardware", "date"],
  ["role", "candidate", "newsstand"],
  ["stable", "refuse", "car"],
  ["storey", "cannibal", "movie"],
  ["elk", "rent", "caption"],
  ["geography", "dilapidation", "hole"],
  ["freighter", "bonus", "hop"],
  ["probability", "petticoat", "emission"],
  ["nucleotidase", "revival", "governance"],
  ["caddy", "glue", "publishing"],
  ["core", "ligand", "scholar"],
  ["head", "motorboat", "swordfight"],
  ["hype", "opium", "locker"],
  ["gang", "coach", "hail"],
  ["snowmobiling", "grandson", "follower"],
  ["jerk", "subcontractor", "modem"],
  ["rawhide", "half-sister", "eye"],
  ["map", "electrocardiogram", "matchmaker"],
  ["pelt", "parameter", "fifth"],
  ["team", "friction", "counseling"],
  ["rope", "socks", "bail"],
  ["midline", "cassava", "creative"],
  ["receptor", "exploration", "cribbage"],
  ["influx", "investor", "farrow"],
  ["muscat", "dioxide", "cry"],
  ["profit", "dime", "maracas"],
  ["normal", "folk", "comedy"],
  ["mid-course", "rainstorm", "basin"],
  ["authenticity", "proponent", "quote"],
  ["textual", "provider", "crewmen"],
  ["killer", "pagan", "settlement"],
  ["instance", "ocelot", "morsel"],
  ["fulfillment", "marketplace", "duration"],
  ["invitation", "hammock", "fine"],
  ["go-kart", "metric", "assignment"],
  ["prow", "insulation", "icing"],
  ["familiar", "marshland", "counsel"],
  ["standard", "blackbird", "driveway"],
  ["bride", "display", "beating"],
  ["cross-stitch", "lifetime", "rations"],
  ["awareness", "entrepreneur", "batting"],
  ["simvastatin", "carpet", "black"],
  ["class", "repair", "love"],
  ["pence", "sort", "condominium"],
  ["critic", "discrimination", "career"],
  ["bun", "mythology", "raven"],
  ["masonry", "stain", "icebreaker"],
  ["burrow", "mantua", "chairman"],
  ["nit", "boolean", "pin"],
  ["dugout", "collision", "polenta"],
  ["fiddle", "honesty", "standoff"],
  ["book", "plover", "comfortable"],
  ["fingerling", "battle", "infiltration"],
  ["bat", "replica", "noon"],
  ["rite", "takeover", "suicide"],
  ["culture", "mezzanine", "problem"],
  ["chinchilla", "sink", "exam"],
  ["invention", "tabby", "heater"],
  ["destination", "asset", "cormorant"],
  ["gossip", "cartilage", "maternity"],
  ["bidding", "kale", "friend"],
  ["paste", "learning", "hostess"],
  ["pint", "pharmacist", "mallet"],
  ["product", "classmate", "ostrich"],
  ["eponym", "mail", "developmental"],
  ["chicory", "dealer", "champion"],
  ["plaintiff", "reach", "photography"],
  ["hiccups", "leading", "oboe"],
  ["review", "exasperation", "hearing"],
  ["installation", "purchase", "gaffer"],
  ["human", "eavesdropper", "index"],
  ["lift", "extinction", "deathwatch"],
  ["diet", "spending", "chrome"],
  ["sex", "age", "chaplain"],
  ["cat", "boysenberry", "mecca"],
  ["ambition", "filly", "difficulty"],
  ["bid", "authorisation", "bump"],
  ["grove", "inhibitor", "initiative"],
  ["gene", "asparagus", "cutover"],
  ["buck", "reserve", "orangutan"],
  ["level", "maple", "embossing"],
  ["babe", "commotion", "maximum"],
  ["baseline", "clergyman", "quiet"],
  ["subgroup", "raffle", "songbird"],
  ["interject", "sticker", "station"],
  ["cylinder", "hardhat", "canoe"],
  ["discharge", "data", "beard"],
  ["caffeine", "tassel", "propaganda"],
  ["jellyfish", "disaster", "clutch"],
  ["glacier", "baboon", "likeness"],
  ["nondisclosure", "increase", "crap"],
  ["implement", "polish", "resale"],
  ["epithelium", "refusal", "coral"],
  ["frown", "mask", "pince-nez"],
  ["cherry", "downforce", "spiritual"],
  ["republic", "output", "damage"],
  ["descent", "codepage", "nod"],
  ["singular", "password", "comb"],
  ["ass", "pace", "acceptance"],
  ["chasm", "face", "style"],
  ["termination", "latitude", "kill"],
  ["stacking", "prejudice", "alder"],
  ["manipulation", "mandate", "lap"],
  ["current", "cheetah", "ficlet"],
  ["buyer", "botany", "fanny-pack"],
  ["advent", "carnation", "fleece"],
  ["steak", "fund", "eyrie"],
  ["chemotaxis", "pricing", "router"],
  ["hawk", "synonym", "floor"],
  ["temptation", "forum", "fourths"],
  ["agent", "bafflement", "prune"],
  ["general", "pennant", "infix"],
  ["congressperson", "cyclamen", "checking"],
  ["criterion", "savannah", "espadrille"],
  ["admin", "opposition", "bibliography"],
  ["snug", "spree", "gamma-ray"],
  ["teriyaki", "program", "midnight"],
  ["talk", "slapstick", "driving"],
  ["professional", "mandolin", "invoice"],
  ["outrigger", "aftershave", "indication"],
  ["lasagna", "kennel", "railing"],
  ["boycott", "marten", "somebody"],
  ["envy", "gravy", "seaweed"],
  ["rim", "neighbor", "accordion"],
  ["programming", "region", "tablecloth"],
  ["tarragon", "molasses", "curriculum"],
  ["section", "pig", "oncology"],
  ["schema", "rat", "blowgun"],
  ["automation", "micronutrient", "siding"],
  ["champagne", "preface", "bitten"],
  ["madam", "forelimb", "ephyra"],
  ["limitation", "decline", "onset"],
  ["brake", "danger", "loneliness"],
  ["ford", "link", "cupcake"],
  ["sunglasses", "homicide", "marimba"],
  ["ketchup", "bunghole", "alb"],
  ["rocket", "spotlight", "keeper"],
  ["character", "spectrograph", "giant"],
  ["shade", "barracks", "battery"],
  ["arena", "communication", "chatter"],
  ["partnership", "goddess", "conversation"],
  ["checkbook", "ideology", "guilt"],
  ["safari", "pretzel", "president"],
  ["accessory", "folklore", "discourse"],
  ["enjoyment", "basis", "reservoir"],
  ["snowsuit", "encyclopedia", "banyan"],
  ["permission", "spinach", "accusation"],
  ["gopher", "limb", "oleo"],
  ["rhubarb", "chauvinist", "loquat"],
  ["panther", "consul", "disappointment"],
  ["pompom", "harp", "spool"],
  ["humidity", "statement", "cauliflower"],
  ["grandmother", "counter", "mink"],
  ["chick", "lotion", "mountain"],
  ["kangaroo", "rudiment", "fanny"],
  ["sorrow", "rosemary", "rediscovery"],
  ["refectory", "agenda", "lysine"],
  ["crane", "clarification", "rebel"],
  ["opportunity", "part", "reward"],
  ["rail", "horse", "monument"],
  ["convention", "goat", "colt"],
  ["manicure", "adviser", "papa"],
  ["riverbed", "daily", "thigh"],
  ["fork", "grill", "mortise"],
  ["playroom", "interface", "relief"],
  ["bronchitis", "bakery", "numismatist"],
  ["pawnshop", "plier", "ghost"],
  ["ground", "crewmate", "activation"],
  ["hunting", "cathedral", "thermostat"],
  ["escalator", "decoder", "rye"],
  ["best-seller", "act", "goodness"],
  ["nonconformist", "field", "adapter"],
  ["parenthesis", "infrastructure", "magic"],
  ["carpenter", "scalp", "sprag"],
  ["impudence", "copy", "accountant"],
  ["hat", "gift", "bolt"],
  ["affidavit", "disruption", "manufacturing"],
  ["quota", "blood", "ashram"],
  ["polyp", "barbeque", "recipient"],
  ["engineering", "sunlight", "eyebrows"],
  ["bomb", "standing", "subsection"],
  ["doggie", "autumn", "suit"],
  ["identification", "guide", "modernist"],
  ["termite", "governor", "eternity"],
  ["duplexer", "sidecar", "creationist"],
  ["marshmallow", "styling", "tendency"],
  ["hazel", "loyalty", "aim"],
  ["praise", "combination", "pony"],
  ["privacy", "butane", "supervision"],
  ["legislator", "kohlrabi", "error"],
  ["competitor", "fetus", "mix"],
  ["countryside", "day", "anterior"],
  ["fridge", "scotch", "mint"],
  ["prince", "ninja", "hatchling"],
  ["scallion", "evocation", "shoat"],
  ["participation", "hill", "bin"],
  ["referendum", "paintwork", "coordination"],
  ["sac", "calendar", "creditor"],
  ["accent", "cygnet", "pinto"],
  ["medal", "idiom", "thread"],
  ["offer", "masterpiece", "beat"],
  ["fact", "feel", "overnighter"],
  ["recall", "gamebird", "automaton"],
  ["commodity", "shoestring", "manor"],
  ["peacock", "break", "club"],
  ["mutton", "pickup", "cobbler"],
  ["range", "metro", "savior"],
  ["desert", "bog", "bikini"],
  ["canteen", "barometer", "detection"],
  ["eating", "memory", "futon"],
  ["draft", "cranky", "naturalisation"],
  ["quiver", "nursing", "locomotive"],
  ["beginning", "encirclement", "resolve"],
  ["banjo", "dependency", "grin"],
  ["arcade", "corporal", "phenotype"],
  ["ore", "milepost", "comestible"],
  ["instrumentation", "comradeship", "caterpillar"],
  ["circulation", "jack", "league"],
  ["pearl", "reef", "spot"],
  ["silence", "gastronomy", "soundness"],
  ["tavern", "husband", "bake"],
  ["gas", "leeway", "symptom"],
  ["blogger", "precision", "omega"],
  ["album", "pathogenesis", "offset"],
  ["ash", "darkness", "steamroller"],
  ["stumbling", "neologism", "adoption"],
  ["perception", "bunch", "language"],
  ["rating", "gold", "cent"],
  ["ephemera", "cough", "exhibit"],
  ["line", "divider", "banner"],
  ["shackle", "dysfunction", "die"],
  ["achievement", "cirrhosis", "original"],
  ["meet", "backdrop", "ambassador"],
  ["study", "bolero", "plight"],
  ["assist", "legging", "sector"],
  ["cocoa", "landform", "nerve"],
  ["dam", "meantime", "pair"],
  ["conscience", "dune buggy", "graduation"],
  ["commitment", "pantry", "intent"],
  ["counter-force", "beret", "diploma"],
  ["position", "lathe", "goldfish"],
  ["export", "acorn", "nicety"],
  ["future", "corporation", "maker"],
  ["self-control", "mosque", "monocle"],
  ["deal", "eel", "coupon"],
  ["displacement", "ejector", "farm"],
  ["few", "slash", "discretion"],
  ["cookie", "recipe", "stroke"],
  ["patrimony", "rag", "heavy"],
  ["merchant", "finding", "fan"],
  ["puppet", "half-brother", "cave"],
  ["teapot", "reporting", "reply"],
  ["convenience", "fishnet", "involvement"],
  ["farmer", "hacienda", "replication"],
  ["conspiracy", "comma", "mangrove"],
  ["antennae", "pump", "eaves"],
  ["contour", "test", "impairment"],
  ["altar", "basket", "cage"],
  ["co-producer", "endive", "anger"],
  ["disagreement", "denominator", "precedent"],
  ["seaside", "characteristic", "brink"],
  ["anorak", "proximal", "ginger"],
  ["cuisine", "elixir", "brandy"],
  ["mimosa", "origin", "spelt"],
  ["damn", "croissant", "anxiety"],
  ["maize", "peace", "premeditation"],
  ["tear", "base", "estrogen"],
  ["personality", "basketball", "dissonance"],
  ["gum", "junket", "newspaper"],
  ["distinction", "capacity", "read"],
  ["kitten", "simplification", "leaf"],
  ["chandelier", "pedal", "men"],
  ["swallow", "nuke", "amber"],
  ["stonework", "prostacyclin", "calm"],
  ["bond", "crate", "blackness"],
  ["hellcat", "fraction", "sandbar"],
  ["abundance", "infection", "drake"],
  ["banquette", "doing", "evidence"],
  ["journal", "hook", "pool"],
  ["drop", "raccoon", "protein"],
  ["grouper", "green", "jeep"],
  ["flan", "health", "disposer"],
  ["spiral", "switchboard", "meander"],
  ["drain", "roommate", "kitsch"],
  ["show-stopper", "pest", "master"],
  ["jumper", "signet", "syndrome"],
  ["solution", "testimonial", "provision"],
  ["hemp", "brand", "pathway"],
  ["conversion", "bonfire", "niche"],
  ["colonialism", "equal", "gateway"],
  ["sheath", "moon", "many"],
  ["sectional", "enquiry", "firewall"],
  ["insectarium", "punishment", "luggage"],
  ["escape", "equation", "density"],
  ["remnant", "agony", "bucket"],
  ["smith", "pupil", "stepmother"],
  ["lead", "analgesia", "eyelash"],
  ["burro", "math", "staff"],
  ["alpenglow", "poetry", "evolution"],
  ["blog", "resource", "living"],
  ["honoree", "sandwich", "beet"],
  ["allocation", "cilantro", "revascularisation"],
  ["candle", "conga", "sweat"],
  ["bus", "cofactor", "confectionery"],
  ["prosperity", "brunch", "manner"],
  ["semicircle", "restaurant", "insurance"],
  ["pocket-watch", "industrialization", "image"],
  ["cause", "register", "raft"],
  ["stiletto", "chiffonier", "crab"],
  ["summer", "motorcar", "attainment"],
  ["neurobiologist", "starboard", "millisecond"],
  ["alpaca", "flight", "documentation"],
  ["council", "calculator", "exile"],
  ["dependent", "cope", "sub"],
  ["removal", "civilian", "scripture"],
  ["graphic", "heat", "bob"],
  ["perch", "fly", "nymph"],
  ["library", "nest", "chronicle"],
  ["edible", "eleventh", "fahrenheit"],
  ["frosting", "picture", "carp"],
  ["knight", "menu", "breakthrough"],
  ["bottle", "testimony", "kayak"],
  ["gobbler", "fries", "chess"],
  ["growth", "skeleton", "salute"],
  ["crazy", "girdle", "deployment"],
  ["snowflake", "point", "scimitar"],
  ["duty", "fire", "fondue"],
  ["jogging", "spleen", "remark"],
  ["pinkie", "irony", "sloth"],
  ["coast", "sovereignty", "thistle"],
  ["fob", "in-laws", "boogeyman"],
  ["chief", "connotation", "similarity"],
  ["meme", "mama", "bather"],
  ["dispute", "interferometer", "reconsideration"],
  ["pencil", "balalaika", "panic"],
  ["mention", "platform", "countess"],
  ["sycamore", "round", "flax"],
  ["riding", "southeast", "ease"],
  ["course", "dragonfly", "brook"],
  ["necessity", "diagram", "sorrel"],
  ["blame", "flour", "paperback"],
  ["octave", "pentagon", "hound"],
  ["heir", "produce", "prophet"],
  ["thinking", "hobby", "drizzle"],
  ["glimpse", "alien", "brain"],
  ["ignorance", "decency", "alpenhorn"],
  ["prior", "crowd", "congress"],
  ["blanket", "clearance", "shack"],
  ["action", "retrospectivity", "kendo"],
  ["quit", "pancreas", "colon"],
  ["temptress", "lye", "soda"],
  ["relation", "soap", "camp"],
  ["sinuosity", "cuckoo", "donation"],
  ["oversight", "dead", "hanger"],
  ["shopping", "driver", "consideration"],
  ["bud", "pelican", "raise"],
  ["dining", "chili", "corridor"],
  ["repeat", "screening", "jaw"],
  ["jailhouse", "motel", "pinafore"],
  ["management", "migrant", "planula"],
  ["inspection", "mascara", "receipt"],
  ["technique", "fairness", "center"],
  ["dearest", "possible", "cuticle"],
  ["cria", "shoe", "gasket"],
  ["pseudoscience", "material", "fatigue"],
  ["front", "ox", "serial"],
  ["bra", "crisp", "handball"],
  ["sarong", "excerpt", "lime"],
  ["improvement", "gander", "dogsled"],
  ["bead", "straw", "home"],
  ["proof", "millstone", "show"],
  ["pressure", "staircase", "opinion"],
  ["system", "daughter", "farming"],
  ["leave", "prayer", "melon"],
  ["glove", "epic", "hurricane"],
  ["galoshes", "producer", "odometer"],
  ["diction", "blazer", "attempt"],
  ["stot", "cell", "albatross"],
  ["feeling", "filing", "buckle"],
  ["raisin", "buddy", "doubt"],
  ["household", "nutmeg", "balloon"],
  ["plum", "confusion", "medicine"],
  ["chocolate", "stall", "contingency"],
  ["couch", "cross", "addiction"],
  ["oeuvre", "decision", "reservation"],
  ["industry", "determination", "tadpole"],
  ["spirituality", "novel", "stuff"],
  ["magnet", "innocent", "condition"],
  ["profession", "earnings", "accomplishment"],
  ["mainland", "junker", "incision"],
  ["cake", "concert", "mower"],
  ["liver", "howard", "responsibility"],
  ["rethinking", "disembodiment", "separation"],
  ["catalysis", "favor", "duck"],
  ["bran", "commonsense", "mechanic"],
  ["peasant", "lunge", "nothing"],
  ["mate", "fava", "navigation"],
  ["campus", "string", "immortal"],
  ["rip", "obsidian", "derby"],
  ["flock", "fiesta", "eyelashes"],
  ["tablet", "designer", "housework"],
  ["disclaimer", "mind", "founder"],
  ["disability", "stadium", "reparation"],
  ["dirt", "conspirator", "rank"],
  ["crude", "biplane", "public"],
  ["marines", "grace", "celebration"],
  ["chino", "intervention", "guarantee"],
  ["cashier", "pseudocode", "climate"],
  ["hose", "mutation", "doe"],
  ["faith", "bacon", "snarl"],
  ["block", "neuron", "morale"],
  ["dude", "burial", "pinworm"],
  ["demand", "constant", "minor-league"],
  ["causeway", "pasture", "hypothesis"],
  ["pheasant", "match", "deficit"],
  ["jungle", "species", "bloodflow"],
  ["afternoon", "leaker", "bongo"],
  ["brownie", "closure", "comprehension"],
  ["assistance", "phenomenon", "fate"],
  ["meridian", "guacamole", "failure"],
  ["gem", "sparrow", "emotion"],
  ["subtitle", "speech", "snap"],
  ["bore", "emergence", "spade"],
  ["tempo", "dose", "swim"],
  ["skate", "jute", "carbon"],
  ["centimeter", "balance", "gerbil"],
  ["chauffeur", "spectacle", "debt"],
  ["daisy", "mousse", "preference"],
  ["garb", "saxophone", "iceberg"],
  ["degradation", "juice", "back"],
  ["reform", "punch", "moment"],
  ["fright", "colleague", "erosion"],
  ["parsley", "reset", "spark"],
  ["petition", "disparity", "mining"],
  ["submarine", "dock", "handmaiden"],
  ["pusher", "idiot", "raincoat"],
  ["stopwatch", "invite", "ruler"],
  ["incandescence", "addition", "oil"],
  ["ironclad", "pit", "lesbian"],
  ["algebra", "subscription", "flexibility"],
  ["gigantism", "discrepancy", "name"],
  ["mess", "strife", "caution"],
  ["cornmeal", "quadrant", "roller"],
  ["golf", "silkworm", "questioner"],
  ["sleet", "dahlia", "contractor"],
  ["shape", "descendant", "tackle"],
  ["enclave", "bread", "intelligence"],
  ["den", "familiarity", "goodnight"],
  ["charset", "loading", "hybridization"],
  ["mangle", "making", "earth"],
  ["pound", "flu", "icon"],
  ["deduce", "marionberry", "guilder"],
  ["recommendation", "millet", "tabernacle"],
  ["arm-rest", "legume", "recognition"],
  ["doorway", "omnivore", "stereo"],
  ["puritan", "freckle", "fluke"],
  ["singing", "quartet", "misogyny"],
  ["coal", "behalf", "bandanna"],
  ["ischemia", "common", "approval"],
  ["leader", "effectiveness", "science"],
  ["off-ramp", "hair", "peer"],
  ["remains", "compensation", "terracotta"],
  ["genius", "running", "stamen"],
  ["impostor", "regret", "humanity"],
  ["migration", "academy", "screw"],
  ["morbidity", "composer", "perpendicular"],
  ["mover", "era", "manager"],
  ["savings", "solvency", "rooster"],
  ["airbag", "rabbi", "incidence"],
  ["hyphenation", "llama", "thumb"],
  ["flower", "exercise", "firm"],
  ["crow", "hunt", "clue"],
  ["pork", "dialect", "monger"],
  ["jar", "flame", "spectacles"],
  ["hive", "liquid", "impropriety"],
  ["inspector", "knife-edge", "finance"],
  ["lox", "councilor", "specialty"],
  ["conditioner", "beech", "loaf"],
  ["room", "jewelry", "bustle"],
  ["councilman", "fairy", "prose"],
  ["spokeswoman", "scenery", "playwright"],
  ["housing", "pan", "state"],
  ["inflation", "biology", "parser"],
  ["key", "plane", "reclamation"],
  ["breakdown", "player", "publication"],
  ["ramen", "captor", "text"],
  ["conclusion", "afterthought", "terrorist"],
  ["situation", "corsage", "ex-wife"],
  ["recapitulation", "sibling", "scorpion"],
  ["ram", "hero", "quest"],
  ["flung", "shawl", "strip"],
  ["chromolithograph", "maelstrom", "molar"],
  ["tailspin", "bottling", "struggle"],
  ["reputation", "claw", "hashtag"],
  ["terrapin", "pate", "appetite"],
  ["filter", "neighborhood", "essay"],
  ["orange", "standpoint", "expose"],
  ["gadget", "dump", "gaiters"],
  ["lay", "omission", "hardboard"],
  ["sculptural", "salad", "spirit"],
  ["diner", "ounce", "bronco"],
  ["handrail", "gland", "integral"],
  ["bourgeoisie", "concentrate", "brocolli"],
  ["granny", "north", "enclosure"],
  ["formal", "hotel", "gaming"],
  ["injury", "insurrection", "celebrity"],
  ["fertilizer", "burlesque", "enrollment"],
  ["habit", "nation", "softening"],
  ["rib", "figure", "blind"],
  ["horseradish", "store", "first"],
  ["julienne", "default", "aunt"],
  ["leisure", "clothing", "sportsman"],
  ["justice", "fax", "nobody"],
  ["grip", "creator", "impediment"],
  ["hospitalization", "bagel", "nose"],
  ["airship", "crib", "hike"],
  ["protection", "coverall", "cartel"],
  ["bidder", "pants", "babushka"],
  ["exhaustion", "cable", "scene"],
  ["litigation", "hint", "apron"],
  ["garment", "bookcase", "overhead"],
  ["squeegee", "seat", "senate"],
  ["flow", "initialize", "sesame"],
  ["competence", "buckwheat", "shell"],
  ["minion", "shin", "linseed"],
  ["report", "bamboo", "postage"],
  ["admission", "ham", "equivalent"],
  ["helicopter", "angle", "investigation"],
  ["labour", "kinase", "brooch"],
  ["clerk", "grant", "elite"],
  ["arch", "erection", "kielbasa"],
  ["leadership", "crepe", "financing"],
  ["fir", "lid", "nutrition"],
  ["scenario", "rabbit", "bratwurst"],
  ["jury", "factor", "freezer"],
  ["elevation", "personal", "mansard"],
  ["coalition", "screen", "container"],
  ["lust", "diving", "rate"],
  ["lining", "scholarship", "cupboard"],
  ["acupuncture", "set", "glass"],
  ["numeracy", "sugar", "peen"],
  ["skin", "statue", "gambling"],
  ["octagon", "inch", "irrigation"],
  ["piss", "synthesis", "pie"],
  ["prescription", "mother-in-law", "backburn"],
  ["diver", "slice", "cure"],
  ["iris", "grandfather", "pillbox"],
  ["handover", "guard", "caftan"],
  ["moth", "birthday", "porpoise"],
  ["mom", "advantage", "haze"],
  ["plunger", "fur", "randomization"],
  ["cub", "noun", "pocket"],
  ["luxury", "dozen", "caviar"],
  ["poncho", "pride", "attribute"],
  ["hen", "tangerine", "nun"],
  ["mailbox", "resemblance", "cirrus"],
  ["checkout", "cigarette", "office"],
  ["donut", "optimisation", "community"],
  ["spectrum", "saucer", "deposition"],
  ["caravan", "access", "crime"],
  ["moonscape", "peak", "knee"],
  ["font", "ordination", "boatload"],
  ["counsellor", "chin", "baseboard"],
  ["satisfaction", "mastoid", "gig"],
  ["proposition", "behavior", "rest"],
  ["linguist", "donor", "neighbour"],
  ["snail", "service", "highway"],
  ["insight", "lout", "tell"],
  ["file", "bacterium", "skunk"],
  ["knuckle", "right", "snowstorm"],
  ["measles", "poppy", "atrium"],
  ["monster", "cooking", "skullcap"],
  ["supermarket", "side", "nitrogen"],
  ["fuel", "manservant", "contagion"],
  ["tenet", "instructor", "outset"],
  ["salami", "gratitude", "tenth"],
  ["forecast", "exaggeration", "population"],
  ["necklace", "finer", "something"],
  ["grammar", "jelly", "desk"],
  ["enemy", "present", "memorial"],
  ["cleat", "odyssey", "advertising"],
  ["cop", "depth", "gran"],
  ["pardon", "south", "ruffle"],
  ["horror", "frame", "chestnut"],
  ["parole", "macaroni", "guy"],
  ["approach", "oyster", "bit"],
  ["conformation", "butcher", "step-father"],
  ["diaper", "execution", "autoimmunity"],
  ["foxglove", "hugger", "devil"],
  ["art", "representative", "peer-to-peer"],
  ["leap", "football", "dresser"],
  ["hydroxyl", "eyestrain", "mist"],
  ["physiology", "destruction", "cot"],
  ["ship", "cloakroom", "ascot"],
  ["seeker", "need", "mastication"],
  ["merit", "defeat", "patrol"],
  ["conference", "stew", "guest"],
  ["fibroblast", "smuggling", "granola"],
  ["soldier", "carboxyl", "printing"],
  ["printer", "spume", "panel"],
  ["everything", "cowbell", "hoe"],
  ["civilization", "dwell", "directory"],
  ["forever", "fortune", "fedora"],
  ["edition", "protest", "literate"],
  ["silly", "machinery", "century"],
  ["chain", "hydrolysis", "sweets"],
  ["generator", "self", "metabolite"],
  ["octopus", "tent", "defense"],
  ["aardvark", "labourer", "scheduling"],
  ["tabletop", "castle", "quinoa"],
  ["source", "apparatus", "casualty"],
  ["energy", "embellishment", "paperwork"],
  ["disregard", "piccolo", "stay"],
  ["privilege", "gondola", "response"],
  ["signify", "lie", "child"],
  ["station-wagon", "surgery", "mother"],
  ["skywalk", "dressing", "cane"],
  ["context", "elver", "observation"],
  ["haunt", "formicarium", "commandment"],
  ["sphynx", "dollop", "incompetence"],
  ["law", "gazebo", "jail"],
  ["coinsurance", "pantsuit", "creature"],
  ["forager", "fireplace", "duel"],
  ["sun", "colonization", "railway"],
  ["slip", "speed", "military"],
  ["combat", "safeguard", "lawsuit"],
  ["might", "jasmine", "metronome"],
  ["sundial", "rape", "semester"],
  ["medication", "stack", "disconnection"],
  ["independent", "bungalow", "crack"],
  ["collaboration", "market", "crook"],
  ["self-confidence", "hood", "leopard"],
  ["disco", "kneejerk", "denim"],
  ["equity", "bulk", "cliff"],
  ["ray", "smoking", "hubcap"],
  ["confirmation", "sunbeam", "palace"],
  ["paddle", "copying", "killing"],
  ["badger", "dress", "smoke"],
  ["surplus", "parliament", "sculpture"],
  ["robin", "clay", "clave"],
  ["deck", "olive", "macaroon"],
  ["strength", "sightseeing", "cut"],
  ["herring", "readiness", "mentor"],
  ["synod", "composition", "nail"],
  ["surfboard", "oatmeal", "idea"],
  ["criteria", "sweatshop", "minimalism"],
  ["mailing", "online", "adjustment"],
  ["smog", "hospitalisation", "paradise"],
  ["cohesion", "minister", "sip"],
  ["mass", "someplace", "progress"],
  ["cappelletti", "surprise", "hamburger"],
  ["exchange", "result", "qualification"],
  ["creationism", "reminder", "complex"],
  ["coil", "hope", "mushroom"],
  ["cardboard", "diffuse", "hesitation"],
  ["bladder", "depressive", "constraint"],
  ["grape", "appetiser", "severity"],
  ["hog", "coaster", "soil"],
  ["liability", "introduction", "platelet"],
  ["archives", "grub", "custody"],
  ["session", "folder", "hearsay"],
  ["culvert", "cameo", "television"],
  ["legacy", "recreation", "motorcycle"],
  ["ringworm", "grab-bag", "drink"],
  ["board", "pharmacopoeia", "revascularization"],
  ["resist", "deadline", "glow"],
  ["enigma", "estate", "tambourine"],
  ["mandarin", "gasp", "burn"],
  ["rocker", "interpretation", "note"],
  ["equality", "anarchist", "pruner"],
  ["dungarees", "bathhouse", "mouser"],
  ["alliance", "evening-wear", "color"],
  ["pocketbook", "composite", "chalet"],
  ["sin", "salary", "miracle"],
  ["pressroom", "dimple", "opening"],
  ["bottom", "diadem", "seashore"],
  ["rise", "paw", "pasta"],
  ["broad", "database", "activist"],
  ["macro", "assistant", "illness"],
  ["disk", "bark", "collagen"],
  ["capitalism", "river", "simplicity"],
  ["burglar", "eyelids", "diaphragm"],
  ["drive", "hacksaw", "nasal"],
  ["browsing", "interpreter", "publisher"],
  ["technologist", "snuck", "desktop"],
  ["missionary", "pilot", "comic"],
  ["arrangement", "personnel", "route"],
  ["infant", "slider", "throat"],
  ["dashboard", "look", "grass"],
  ["competition", "registry", "jeans"],
  ["mosquito", "spine", "puzzle"],
  ["hotdog", "antler", "cultivar"],
  ["premier", "sausage", "nurture"],
  ["sympathy", "reveal", "notoriety"],
  ["rambler", "lawmaker", "script"],
  ["corduroy", "harmony", "phrasing"],
  ["shoulder", "inhabitant", "orchard"],
  ["definition", "cheer", "custom"],
  ["probation", "cuff-link", "lot"],
  ["season", "seep", "direction"],
  ["diam", "eggplant", "attention"],
  ["setting", "full", "gravitas"],
  ["dragonfruit", "duckling", "heating"],
  ["supernatural", "broker", "missile"],
  ["helmet", "client", "garlic"],
  ["foodstuffs", "shot", "chart"],
  ["happening", "fellow", "hand"],
  ["airforce", "moat", "miter"],
  ["hammer", "poster", "daddy"],
  ["bell", "tender", "indigence"],
  ["ammunition", "osmosis", "peripheral"],
  ["creek", "pomelo", "perennial"],
  ["coat", "pill", "sweatsuit"],
  ["beach", "supervisor", "secrecy"],
  ["photo", "recliner", "rubric"],
  ["ceramics", "electricity", "box"],
  ["scientist", "shootdown", "beetle"],
  ["junior", "animal", "snake"],
  ["billboard", "heart", "academics"],
  ["armor", "cooperation", "haversack"],
  ["bridge", "loincloth", "perspective"],
  ["ornament", "gymnastics", "quiche"],
  ["pastor", "nutrient", "step"],
  ["model", "pier", "anklet"],
  ["shine", "rotation", "clove"],
  ["crust", "basics", "emerald"],
  ["hurry", "skylight", "registration"],
  ["classroom", "avalanche", "brochure"],
  ["cape", "refund", "target"],
  ["array", "citizen", "sardine"],
  ["colloquy", "bottom-line", "meaning"],
  ["expectation", "promise", "blueberry"],
  ["pod", "lipstick", "defendant"],
  ["hearth", "angora", "favorite"],
  ["councilperson", "thief", "backbone"],
  ["blocker", "expedition", "schizophrenic"],
  ["newsprint", "item", "eardrum"],
  ["insolence", "falling-out", "centre"],
  ["spat", "impulse", "jet"],
  ["peacoat", "scale", "placement"],
  ["optimist", "owner", "appeal"],
  ["cornet", "burrito", "flip-flops"],
  ["pita", "locket", "issue"],
  ["passing", "anatomy", "food"],
  ["login", "cockroach", "hoof"],
  ["lava", "fight", "handlebar"],
  ["application", "cloves", "clarinet"],
  ["schedule", "question", "emphasis"],
  ["objection", "carbohydrate", "paranoia"],
  ["fiber", "fill", "advance"],
  ["anybody", "bookend", "powder"],
  ["antelope", "organising", "scorn"],
  ["certainty", "scraper", "airplane"],
  ["neck", "inversion", "heirloom"],
  ["anteater", "cloudburst", "lumber"],
  ["circumference", "eraser", "appliance"],
  ["swivel", "ideal", "macaw"],
  ["explanation", "award", "contention"],
  ["licence", "snob", "almond"],
  ["furnace", "runner", "beverage"],
  ["pack", "sunset", "sideboard"],
  ["prairie", "declination", "concrete"],
  ["blade", "itinerary", "seller"],
  ["derivative", "survivor", "crunch"],
  ["platypus", "detector", "brace"],
  ["band", "integration", "chef"],
  ["malice", "finger", "blow"],
  ["boyhood", "marmalade", "architecture"],
  ["TV", "melatonin", "standardization"],
  ["booster", "jackfruit", "bandwidth"],
  ["lever", "palate", "beaver"],
  ["credenza", "fox", "netsuke"],
  ["sewer", "focus", "socialist"],
  ["pilgrimage", "lute", "headrest"],
  ["boom", "congressman", "clinic"],
  ["blackberry", "notepad", "hourglass"],
  ["stencil", "series", "brass"],
  ["somewhere", "lemon", "solicitation"],
  ["subway", "interval", "inauguration"],
  ["exterior", "employment", "cabbage"],
  ["ingrate", "steeple", "accommodation"],
  ["sparerib", "litmus", "joint"],
  ["jacket", "herb", "attendant"],
  ["refrigerator", "beer", "knickers"],
  ["heartbeat", "meatloaf", "billion"],
  ["switch", "geek", "lycra"],
  ["bifocals", "sandal", "nightclub"],
  ["igloo", "integer", "frog"],
  ["columnist", "plowman", "headline"],
  ["con", "panty", "embassy"],
  ["designation", "postfix", "ballot"],
  ["democrat", "technology", "lack"],
  ["mocha", "pickle", "bonnet"],
  ["retirement", "press", "spoon"],
  ["airfield", "t-shirt", "airbus"],
  ["rear", "lipoprotein", "homosexual"],
  ["croup", "ovary", "restroom"],
  ["thrust", "retrospective", "shock"],
  ["monkey", "crewman", "macrame"],
  ["heifer", "consist", "ritual"],
  ["prostanoid", "endpoint", "prestige"],
  ["shutdown", "supreme", "alluvium"],
  ["malnutrition", "spreadsheet", "cassock"],
  ["good-bye", "surroundings", "mattress"],
  ["confidence", "amusement", "crayfish"],
  ["pavilion", "awe", "barge"],
  ["innovation", "cougar", "son"],
  ["housewife", "cemetery", "forage"],
  ["cod", "freight", "fritter"],
  ["diamond", "neonate", "donkey"],
  ["porch", "sensitivity", "enzyme"],
  ["music-making", "crush", "allowance"],
  ["fighter", "cloister", "smell"],
  ["effector", "infarction", "structure"],
  ["artificer", "originality", "form"],
  ["analytics", "stove", "theme"],
  ["plume", "death", "lad"],
  ["segment", "movement", "cargo"],
  ["communion", "chive", "karate"],
  ["syndicate", "estimate", "doctorate"],
  ["dictionary", "slide", "ambience"],
  ["guerrilla", "instrument", "half"],
  ["harmonise", "sunshine", "appellation"],
  ["theory", "lightning", "jockey"],
  ["moai", "quail", "individual"],
  ["spasm", "dogwood", "astrologer"],
  ["billing", "bend", "maintenance"],
  ["dueling", "attendance", "ceramic"],
  ["number", "fisherman", "shift"],
  ["salon", "diversity", "real"],
  ["purple", "tail", "misunderstand"],
  ["bloomer", "illustration", "childhood"],
  ["objective", "celeriac", "sneeze"],
  ["initialise", "rehospitalisation", "realm"],
  ["quartz", "squirrel", "dignity"],
  ["dish", "mobility", "marxism"],
  ["quill", "mystery", "advertisement"],
  ["bagpipe", "stopsign", "gymnast"],
  ["contribution", "painting", "apse"],
  ["birch", "gravel", "larch"],
  ["power", "creme brulee", "availability"],
  ["passage", "chill", "digestion"],
  ["fundraising", "sheep", "particle"],
  ["nightgown", "disdain", "rubber"],
  ["mercury", "canvas", "cup"],
  ["jiffy", "due", "fort"],
  ["horst", "ladder", "developing"],
  ["bosom", "pacemaker", "digger"],
  ["pottery", "pantology", "footage"],
  ["cephalopod", "citrus", "mailman"],
  ["skill", "cummerbund", "alternative"],
  ["pilgrim", "negotiation", "method"],
  ["plea", "conservative", "fraud"],
  ["skyscraper", "major-league", "gathering"],
  ["anagram", "bone", "causal"],
  ["almighty", "significance", "magnitude"],
  ["peninsula", "commercial", "sousaphone"],
  ["stab", "mixer", "muscatel"],
  ["chrysalis", "behold", "rule"],
  ["flash", "nightmare", "glut"],
  ["tattler", "strawberry", "curse"],
  ["mincemeat", "liquor", "dome"],
  ["research", "asterisk", "chaise"],
  ["misnomer", "pitching", "bait"],
  ["rage", "castanet", "breadcrumb"],
  ["sitar", "license", "lookout"],
  ["craftsman", "gall-bladder", "outfit"],
  ["cation", "territory", "jumbo"],
  ["heartache", "maid", "artichoke"],
  ["eyebrow", "executor", "swan"],
  ["maniac", "coverage", "bitter"],
  ["saloon", "chip", "lecture"],
  ["taxicab", "author", "daylight"],
  ["republican", "saw", "shear"],
  ["signal", "motion", "elongation"],
  ["patience", "anthropology", "bronze"],
  ["fringe", "cowboy", "ping"],
  ["moron", "clipper", "parable"],
  ["heel", "excitement", "ozone"],
  ["supporter", "rutabaga", "racist"],
  ["particular", "crewmember", "tamale"],
  ["period", "hometown", "ottoman"],
  ["overflight", "remote", "accompanist"],
  ["inbox", "button", "atelier"],
  ["seagull", "accounting", "cheddar"],
  ["message", "championship", "slipper"],
  ["normalisation", "messenger", "closing"],
  ["snowplow", "skirt", "collar"],
  ["combine", "footstool", "sunroom"],
  ["stranger", "aspic", "tatami"],
  ["spyglass", "handful", "aspect"],
  ["revenue", "dame", "pet"],
  ["fowl", "threshold", "discovery"],
  ["intervenor", "copyright", "barbecue"],
  ["clank", "synergy", "activity"],
  ["corn", "cosset", "bijou"],
  ["airmail", "plow", "spice"],
  ["nibble", "investment", "thirst"],
  ["discussion", "lag", "stone"],
  ["providence", "platinum", "abbreviation"],
  ["prison", "easel", "rider"],
  ["magazine", "epauliere", "proceedings"],
  ["former", "flint", "atheist"],
  ["backyard", "hippodrome", "format"],
  ["statistics", "oats", "sherbet"],
  ["epoch", "mitten", "prize"],
  ["literature", "sushi", "flytrap"],
  ["evaluation", "porcupine", "mechanism"],
  ["sustenance", "pike", "evil"],
  ["outlay", "regulation", "aircraft"],
  ["modeling", "serum", "quince"],
  ["campanile", "divan", "deposit"],
  ["patriarch", "musician", "eurocentrism"],
  ["pianist", "ark", "antiquity"],
  ["crystallography", "efficacy", "breadfruit"],
  ["attraction", "microlending", "premise"],
  ["orchestra", "ancestor", "sailboat"],
  ["taxi", "decongestant", "snowman"],
  ["necktie", "dill", "cascade"],
  ["dolor", "practitioner", "stability"],
  ["salesman", "choir", "dust"],
  ["reception", "sidestream", "cement"],
  ["ribbon", "scallops", "flare"],
  ["minimum", "rebellion", "populist"],
  ["lawyer", "emanate", "hello"],
  ["organizing", "argument", "snakebite"],
  ["outlet", "regime", "pepperoni"],
  ["homeland", "ectoderm", "melody"],
  ["imitation", "bullet", "shoemaker"],
  ["neon", "manufacturer", "broom"],
  ["outcome", "retreat", "inventor"],
  ["baseball", "graph", "lobotomy"],
  ["sweater", "chimpanzee", "calculus"],
  ["reasoning", "abortion", "gearshift"],
  ["harbour", "spider", "cactus"],
  ["contributor", "step-mother", "sorbet"],
  ["garden", "cappuccino", "supper"],
  ["jodhpurs", "consumer", "interloper"],
  ["innervation", "consent", "industrialisation"],
  ["month", "charity", "hubris"],
  ["pouch", "alligator", "shadow"],
  ["consulting", "swine", "compulsion"],
  ["bath", "assessment", "locality"],
  ["coleslaw", "shoe-horn", "thongs"],
  ["laborer", "pressurisation", "accelerant"],
  ["shingle", "hatbox", "stepdaughter"],
  ["catsup", "greenhouse", "fiberglass"],
  ["marker", "dumbwaiter", "handicap"],
  ["hydrogen", "downtown", "spatula"],
  ["dot", "subject", "buggy"],
  ["doubter", "meteor", "deputy"],
  ["charter", "coonskin", "applewood"],
  ["berry", "antling", "clock"],
  ["mime", "drill", "going"],
  ["broccoli", "body", "insomnia"],
  ["goal", "logistics", "craft"],
  ["abnormality", "advocate", "gray"],
  ["beastie", "hearthside", "ranch"],
  ["artery", "fishery", "greens"],
  ["gain", "accordance", "being"],
  ["protocol", "steward", "doorknob"],
  ["release", "loss", "surgeon"],
  ["teaching", "mukluk", "feng"],
  ["passport", "fugato", "cloak"],
  ["programme", "noir", "carriage"],
  ["rock", "mobile", "life"],
  ["actor", "squid", "ruckus"],
  ["rap", "holder", "cobweb"],
  ["simple", "backpack", "frost"],
  ["digestive", "lab", "care"],
  ["baker", "gnu", "licensing"],
  ["slime", "airline", "subroutine"],
  ["crumb", "chit-chat", "instinct"],
  ["revenant", "currant", "footrest"],
  ["extension", "streetcar", "effacement"],
  ["aid", "greed", "lacquerware"],
  ["atom", "abacus", "softball"],
  ["ethics", "covariate", "buzzard"],
  ["kimono", "harbor", "mutt"],
  ["curve", "laparoscope", "boon"],
  ["checkroom", "lane", "dance"],
  ["commission", "siege", "archaeologist"],
  ["racism", "alteration", "pond"],
  ["kite", "rose", "copywriter"],
  ["pathology", "roadway", "chronometer"],
  ["balaclava", "dragon", "leash"],
  ["pinot", "empire", "mortal"],
  ["candelabra", "armoire", "communicant"],
  ["comment", "hamster", "building"],
  ["principal", "sprat", "foam"],
  ["cynic", "hummus", "thesis"],
  ["lyrics", "clef", "practice"],
  ["paramecium", "forest", "pard"],
  ["camel", "parcel", "dollar"],
  ["honeydew", "flat", "temple"],
  ["alphabet", "sum", "bough"],
  ["people", "oak", "continent"],
  ["redesign", "eggnog", "perfection"],
  ["root", "boy", "challenge"],
  ["reindeer", "outline", "parent"],
  ["ridge", "earring", "okra"],
  ["attack", "explorer", "counselor"],
  ["hierarchy", "polyester", "endorsement"],
  ["developer", "democracy", "gong"],
  ["realization", "ego", "neuropsychiatry"],
  ["acre", "subprime", "iridescence"],
  ["disease", "hockey", "randomisation"],
  ["dolphin", "impact", "libido"],
  ["geyser", "orientation", "answer"],
  ["airman", "stream", "fat"],
  ["metallurgist", "interaction", "split"],
  ["ordinary", "official", "miscommunication"],
  ["dragster", "arthur", "liner"],
  ["facelift", "sucker", "fold"],
  ["sanity", "domain", "feather"],
  ["recess", "pitcher", "fry"],
  ["honey", "ski", "majority"],
  ["shield", "inspiration", "gazelle"],
  ["pleasure", "asphalt", "speaking"],
  ["terror", "compliment", "pinstripe"],
  ["believer", "flag", "ant"],
  ["chorus", "min", "basement"],
  ["comparison", "hardening", "halibut"],
  ["grasp", "pith", "circumstance"],
  ["souvenir", "label", "defender"],
  ["publicity", "bathrobe", "hovel"],
  ["obstacle", "term", "cupola"],
  ["scent", "representation", "capital"],
  ["avocado", "leprosy", "organization"],
  ["someone", "plot", "ferret"],
  ["terminal", "chops", "mode"],
  ["hate", "earmuffs", "bunkhouse"],
  ["draw", "floozie", "minnow"],
  ["operation", "alley", "pyridine"],
  ["flood", "analog", "mayor"],
  ["indicator", "ice", "observatory"],
  ["payee", "duffel", "peach"],
  ["formation", "plumber", "bull-fighter"],
  ["margarine", "compress", "drainage"],
  ["shortage", "octavo", "helium"],
  ["bed", "department", "litter"],
  ["bumper", "construction", "sentencing"],
  ["dentist", "revolver", "sidewalk"],
  ["hiring", "monk", "mixture"],
  ["most", "logic", "clothes"],
  ["divalent", "kilogram", "support"],
  ["plenty", "catamaran", "bet"],
  ["signature", "lyocell", "footwear"],
  ["history", "blizzard", "suggestion"],
  ["cereal", "grapefruit", "shofar"],
  ["presentation", "intellect", "manatee"],
  ["slope", "sweatshirt", "ruby"],
  ["choker", "ability", "scrap"],
  ["analyst", "size", "node"],
  ["church", "resume", "inverse"],
  ["luncheonette", "reorganization", "tank"],
  ["dickey", "sea", "interview"],
  ["lobster", "giraffe", "lieutenant"],
  ["eicosanoid", "lake", "astrolabe"],
  ["blight", "pledge", "reversal"],
  ["kid", "fibre", "boxer"],
  ["delivery", "seal", "sampan"],
  ["tankful", "exit", "burn-out"],
  ["harmonica", "radiator", "hour"],
  ["catacomb", "gun", "humour"],
  ["rally", "shallot", "cellar"],
  ["counterpart", "entrance", "hardcover"],
  ["researcher", "bust", "cattle"],
  ["swamp", "complexity", "chowder"],
  ["headphones", "jam", "netbook"],
  ["quarter", "carry", "paddock"],
  ["guava", "success", "promenade"],
  ["eaglet", "document", "jumpsuit"],
  ["texture", "rayon", "burst"],
  ["homework", "divine", "beam"],
  ["fashion", "kitchen", "exhibition"],
  ["rumor", "carving", "carnival"],
  ["tentacle", "reciprocity", "robe"],
  ["inability", "citizenship", "cast"],
  ["squatter", "comfort", "cleaner"],
  ["gynaecology", "bathtub", "hurt"],
  ["gear", "compromise", "birth"],
  ["clearing", "discount", "angina"],
  ["crocodile", "stair", "bribery"],
  ["party", "forearm", "stallion"],
  ["beheading", "hydrocarb", "patina"],
  ["friendship", "primary", "rugby"],
  ["security", "reporter", "scout"],
  ["pendulum", "lung", "sponsor"],
  ["fragrance", "clavier", "cyclooxygenase"],
  ["dynasty", "peanut", "bricklaying"],
  ["piglet", "geology", "pantologist"],
  ["guitar", "prey", "recollection"],
  ["lymphocyte", "nourishment", "miscarriage"],
  ["annual", "opossum", "philanthropy"],
  ["subsidence", "dromedary", "lychee"],
  ["editorial", "grandmom", "barley"],
  ["length", "physical", "metal"],
  ["boar", "exception", "silver"],
  ["coffin", "load", "property"],
  ["mallard", "hectare", "reprocessing"],
  ["disguise", "calculation", "glockenspiel"],
  ["spill", "barrier", "final"],
  ["dart", "marsh", "blackfish"],
  ["agency", "sound", "gale"],
  ["scarecrow", "oval", "screw-up"],
  ["punctuation", "cruise", "lifestyle"],
  ["land", "conception", "measure"],
  ["complaint", "gram", "alert"],
  ["retailer", "sentence", "maintainer"],
  ["savory", "crackers", "gauge"],
  ["corps", "meat", "border"],
  ["promotion", "buffer", "overshoot"],
  ["temporariness", "surge", "brushing"],
  ["complement", "shopper", "blend"],
  ["snuggle", "satin", "pamphlet"],
  ["organ", "journalism", "genocide"],
  ["pattern", "chasuble", "junk"],
  ["philosopher", "reading", "belfry"],
  ["theism", "spray", "hip"],
  ["spruce", "listening", "antibody"],
  ["step-grandfather", "lover", "matter"],
  ["osprey", "plaster", "carol"],
  ["mission", "convert", "clone"],
  ["dinosaur", "stock-in-trade", "newsletter"],
  ["strawman", "economics", "hub"],
  ["anticodon", "experience", "downturn"],
  ["circle", "median", "guess"],
  ["patty", "studio", "slump"],
  ["pecker", "ceiling", "dictaphone"],
  ["fix", "belief", "in-joke"],
  ["popularity", "dough", "gavel"],
  ["kettledrum", "bombing", "riddle"],
  ["scooter", "examiner", "acknowledgment"],
  ["sick", "elm", "grandparent"],
  ["seafood", "playground", "comptroller"],
  ["plan", "tension", "jewellery"],
  ["knot", "gripper", "collectivisation"],
  ["progenitor", "bonding", "assassination"],
  ["dancing", "step-uncle", "impression"],
  ["harvester", "rectangle", "kilometer"],
  ["harpooner", "nursery", "shoes"],
  ["mark", "liquidity", "revitalisation"],
  ["marksman", "sheet", "pickaxe"],
  ["presidency", "slavery", "purr"],
  ["grouse", "founding", "armadillo"],
  ["CD", "encounter", "precedence"],
  ["modification", "status", "double"],
  ["brilliant", "east", "plough"],
  ["great-grandfather", "battleship", "bartender"],
  ["sale", "android", "amendment"],
  ["casino", "contest", "piano"],
  ["myth", "article", "ATM"],
  ["hatred", "escort", "loft"],
  ["deformation", "arrogance", "git"],
  ["mozzarella", "mistake", "casket"],
  ["brewer", "latex", "task"],
  ["cantaloupe", "digit", "table"],
  ["exclamation", "cadet", "mortgage"],
  ["shaker", "essential", "teammate"],
  ["puggle", "pot", "cornflakes"],
  ["agreement", "pegboard", "stealth"],
  ["speculation", "cartoon", "crusader"],
  ["forte", "meadow", "gym"],
  ["boundary", "correspondent", "deer"],
  ["cockpit", "monotheism", "pirate"],
  ["bug", "terrace", "overload"],
  ["inside", "loophole", "exposition"],
  ["chap", "dynamics", "peek"],
  ["alloy", "shoelace", "degree"],
  ["philosophy", "reference", "hornet"],
  ["arch-rival", "budget", "anime"],
  ["stamina", "apprehension", "fiction"],
  ["motive", "beggar", "hake"],
  ["moustache", "hexagon", "infancy"],
  ["cricket", "reinscription", "quicksand"],
  ["redhead", "cholesterol", "analogue"],
  ["beauty", "compassionate", "niece"],
  ["atmosphere", "neglect", "blowhole"],
  ["dilution", "nephew", "liberty"],
  ["photographer", "gaffe", "canopy"],
  ["charlatan", "space", "terminology"],
  ["plugin", "cord", "hospital"],
  ["shit", "potato", "recovery"],
  ["celery", "frustration", "compost"],
  ["existence", "guilty", "panda"],
  ["chutney", "carrier", "napkin"],
  ["bass", "charge", "primate"],
  ["detour", "dedication", "domination"],
  ["boxspring", "outfielder", "government"],
  ["roundabout", "taxpayer", "ride"],
  ["kiss", "commerce", "fault"],
  ["haste", "octet", "baggie"],
  ["stump", "pay", "park"],
  ["compass", "currency", "copper"],
  ["figurine", "description", "ferryboat"],
  ["return", "coconut", "advice"],
  ["poker", "crocus", "poverty"],
  ["pimp", "parka", "mud"],
  ["shelf", "stag", "family"],
  ["chance", "kind", "breastplate"],
  ["adverb", "soulmate", "specialist"],
  ["buffalo", "goodie", "bidet"],
  ["endoderm", "supply", "forehead"],
  ["decade", "chassis", "browser"],
  ["patch", "hormone", "taco"],
  ["grid", "beneficiary", "offense"],
  ["relative", "hedge", "skull"],
  ["chime", "phosphate", "romance"],
  ["ruin", "emergency", "mortality"],
  ["hunchback", "hand-holding", "card"],
  ["cop-out", "blouse", "catastrophe"],
  ["bandana", "inflammation", "tart"],
  ["canon", "laptop", "salsa"],
  ["depot", "anything", "sash"],
  ["query", "chair", "thousand"],
  ["prefix", "pun", "rancher"],
  ["banker", "night", "catch"],
  ["chest", "reunion", "laugh"],
  ["boatyard", "scarf", "consumption"],
  ["mango", "shark", "globe"],
  ["chug", "racer", "applause"],
  ["filth", "chipmunk", "repayment"],
  ["song", "authentication", "keep"],
  ["sack", "jellybeans", "decryption"],
  ["penguin", "left", "prosecution"],
  ["accuracy", "inhibition", "bassoon"],
  ["tactics", "count", "parenting"],
  ["fall", "aluminum", "eve"],
  ["moose", "placode", "sender"],
  ["premium", "education", "durian"],
  ["rhetoric", "preservation", "codpiece"],
  ["seminar", "consciousness", "implementation"],
  ["storage", "dictator", "hit"],
  ["credibility", "priest", "porcelain"],
  ["row", "ligula", "screamer"],
  ["society", "sport", "import"],
  ["daffodil", "adjective", "pressurization"],
  ["lamp", "subset", "runaway"],
  ["cafe", "slang", "airport"],
  ["prizefight", "cartload", "ad"],
  ["endothelium", "adult", "monitor"],
  ["slot", "command", "bowtie"],
  ["retrospect", "boss", "tattoo"],
  ["rain", "snack", "bankruptcy"],
  ["apple", "meter", "puffin"],
  ["leveret", "crucifixion", "experimentation"],
  ["rehospitalization", "proposal", "halt"],
  ["spy", "hygienic", "detail"],
  ["admire", "owl", "stole"],
  ["talking", "saving", "muscle"],
  ["decision-making", "crew", "festival"],
  ["archaeology", "federation", "spell"],
  ["photograph", "sledge", "feed"],
  ["lollipop", "clavicle", "sari"],
  ["cheesecake", "pipeline", "sulfur"],
  ["establishment", "immigrant", "drawer"],
  ["stock", "pulse", "chopstick"],
  ["father", "audit", "alarm"],
  ["pattypan", "costume", "cover"],
  ["genie", "suede", "hippopotamus"],
  ["justification", "component", "silk"],
  ["house", "pile", "shakedown"],
  ["swordfish", "homonym", "email"],
  ["goggles", "plastic", "furry"],
  ["chainstay", "graduate", "hosiery"],
  ["collectivization", "consensus", "hospitality"],
  ["fedelini", "employer", "brow"],
  ["senator", "principle", "mobster"],
  ["tactile", "branch", "cashew"],
  ["cutting", "palm", "dealing"],
  ["lobby", "occurrence", "jazz"],
  ["macrofauna", "gesture", "cycle"],
  ["meringue", "neuropathologist", "baritone"],
  ["cork", "pigeon", "enactment"],
  ["extent", "centurion", "dimension"],
  ["asymmetry", "stucco", "fail"],
  ["freezing", "exocrine", "headache"],
  ["mill", "facet", "rowboat"],
  ["audience", "puma", "samovar"],
  ["knowledge", "dessert", "highlight"],
  ["heroine", "flugelhorn", "noise"],
  ["campaigning", "campaign", "sensor"],
  ["pastry", "duster", "portfolio"],
  ["coke", "compassion", "fence"],
  ["kick-off", "teletype", "account"],
  ["scope", "auto", "ectodermal"],
  ["decimal", "price", "cytokine"],
  ["gallery", "outback", "hold"],
  ["landmine", "jot", "mouse"],
  ["expert", "subsidiary", "mast"],
  ["conservation", "laughter", "pounding"],
  ["adaptation", "breast", "garter"],
  ["brood", "brick", "star"],
  ["bicycle", "arithmetic", "phone"],
  ["hydrofoil", "leek", "glen"],
  ["street", "tap", "shipyard"],
  ["race", "drinking", "king"],
  ["development", "port", "starter"],
  ["purity", "percentage", "impala"],
  ["spank", "dynamite", "object"],
  ["noodle", "mantel", "explosion"],
  ["nickname", "start", "threat"],
  ["cloth", "locust", "student"],
  ["anarchy", "ecliptic", "solidarity"],
  ["recruit", "downstairs", "demur"],
  ["motivation", "fawn", "content"],
  ["booklet", "stem", "drawing"],
  ["periodical", "authority", "hallway"],
  ["spokesman", "fantasy", "mare"],
  ["soliloquy", "bonsai", "farmland"],
  ["reason", "archer", "environment"],
  ["bank", "daikon", "antique"],
  ["handgun", "exposure", "moody"],
  ["inventory", "dispatch", "backup"],
  ["lemonade", "choosing", "hyacinth"],
  ["means", "grease", "conduct"],
  ["cushion", "dial", "regulator"],
  ["relationship", "organisation", "sage"],
  ["molding", "oasis", "ethnicity"],
  ["purpose", "curtailment", "mean"],
  ["captain", "lapdog", "prevention"],
  ["shoreline", "behaviour", "information"],
  ["clipboard", "max", "digging"],
  ["afterlife", "hypothermia", "doctrine"],
  ["cornerstone", "pollutant", "credential"],
  ["eyeglasses", "doubling", "boulder"],
  ["psychoanalyst", "ketch", "eclipse"],
  ["auction", "linen", "stepson"],
  ["rush", "homosexuality", "fascia"],
  ["anesthesiologist", "sample", "sandpaper"],
  ["catcher", "excuse", "knife"],
  ["patentee", "inglenook", "shrine"],
  ["shanty", "differential", "contact"],
  ["crawdad", "thickness", "recession"],
  ["mine", "excellence", "apparel"],
  ["raid", "fame", "essence"],
  ["cocktail", "cranberry", "decadence"],
  ["seabass", "couple", "mariachi"],
  ["corner", "acetate", "dawn"],
  ["luck", "everyone", "popsicle"],
  ["inclusion", "buffet", "distribution"],
  ["lesson", "milestone", "engagement"],
  ["apartment", "settler", "baby"],
  ["reliability", "sleuth", "abrogation"],
  ["maestro", "smelting", "steam"],
  ["genre", "menorah", "harpsichord"],
  ["prompt", "giggle", "order"],
  ["deliberation", "guestbook", "operator"],
  ["membership", "ingredient", "step-daughter"],
  ["pail", "phrase", "teenager"],
  ["legislation", "fit", "hackwork"],
  ["builder", "mustard", "semicolon"],
  ["step-grandmother", "sock", "ambiguity"],
  ["limit", "eyeball", "pantyhose"],
  ["detainee", "polarisation", "bias"],
  ["tepee", "boulevard", "microwave"],
  ["microphone", "lottery", "gutter"],
  ["letter", "geometry", "poem"],
  ["assault", "icecream", "imagination"],
  ["scrambled", "memo", "barstool"],
  ["fennel", "nectarine", "manacle"],
  ["refreshments", "story-telling", "altitude"],
  ["expansionism", "journey", "proportion"],
  ["butler", "marketing", "hydrocarbon"],
  ["flesh", "actress", "experiment"],
  ["male", "gender", "stand"],
  ["supplement", "enthusiasm", "entity"],
  ["lock", "poor", "island"],
  ["circadian", "skean", "servitude"],
  ["hiking", "share", "function"],
  ["notebook", "dynamo", "health-care"],
  ["jicama", "pilaf", "snorer"],
  ["institution", "ethyl", "slate"],
  ["temp", "airfare", "camper"],
  ["downfall", "eyeliner", "flintlock"],
  ["faculty", "fresco", "address"],
  ["septicaemia", "female", "dash"],
  ["red", "inconvenience", "teller"],
  ["pudding", "pigsty", "sombrero"],
  ["option", "leptocephalus", "entirety"],
  ["complication", "ratio", "nightingale"],
  ["secret", "great-grandmother", "professor"],
  ["bobcat", "retina", "dinghy"],
  ["story", "graffiti", "steel"],
  ["outlook", "collapse", "adulthood"],
  ["scrutiny", "employee", "insurgence"],
  ["nonbeliever", "coordinator", "senior"],
  ["cleric", "still", "hunger"],
  ["aquifer", "shallows", "light"],
  ["belligerency", "booty", "revenge"],
  ["biosphere", "peony", "plantation"],
  ["freon", "summit", "panpipe"],
  ["breeze", "associate", "business"],
  ["fleck", "invasion", "menopause"],
  ["inscription", "debtor", "scanner"],
  ["sauce", "intercourse", "sprinkles"],
  ["processor", "lounge", "appreciation"],
  ["calorie", "adrenalin", "blister"],
  ["dandelion", "parade", "roll"],
  ["athletics", "massage", "blossom"],
  ["forebear", "coliseum", "emitter"],
  ["chastity", "dwelling", "suspension"],
  ["inheritance", "leg", "partridge"],
  ["communist", "passive", "bill"],
  ["alibi", "imprisonment", "freak"],
  ["completion", "agriculture", "koala"],
  ["naming", "doorbell", "assembly"],
  ["barber", "bandolier", "plug"],
  ["brushfire", "cancer", "crystal"],
  ["cravat", "antecedent", "close"],
  ["step-aunt", "fishbone", "harm"],
  ["reader", "earthquake", "bowl"],
  ["humor", "nickel", "overweight"],
  ["hybridisation", "stress", "labor"],
  ["ocean", "spite", "sight"],
  ["dreamer", "factory", "residue"],
  ["cold", "parrot", "coyote"],
  ["restriction", "procurement", "site"],
  ["gradient", "distributor", "honor"],
  ["special", "horn", "aside"],
  ["abuse", "thug", "arrival"],
  ["elevator", "controller", "appointment"],
  ["creche", "aggression", "functionality"],
  ["dip", "jeweller", "tennis"],
  ["pecan", "lord", "egg"],
  ["patio", "mailer", "briefly"],
  ["gorilla", "sunflower", "mapping"],
  ["statin", "subsidy", "popcorn"],
  ["rack", "poultry", "heartwood"],
  ["renaissance", "lawn", "robot"],
  ["put", "tenor", "pass"],
  ["illusion", "c-clamp", "main"],
  ["gel", "enterprise", "earrings"],
  ["racing", "school", "balcony"],
  ["rake", "device", "architect"],
  ["earplug", "consistency", "angstrom"],
  ["hire", "receiver", "secretion"],
  ["midwife", "rum", "spouse"],
  ["petal", "gentleman", "hermit"],
  ["therapy", "risk", "parachute"],
  ["buy", "jalapeño", "permit"],
  ["pregnancy", "detainment", "span"],
  ["nestling", "sole", "square"],
  ["broiler", "matrix", "placebo"],
  ["bulldozer", "advocacy", "shrimp"],
  ["production", "mat", "hug"],
  ["mug", "satire", "hurdler"],
  ["engineer", "overclocking", "rocket-ship"],
  ["buzz", "apology", "businessman"],
  ["pole", "package", "gate"],
  ["score", "deodorant", "fisting"],
  ["dissemination", "carrot", "morning"],
  ["performance", "doughnut", "bowler"],
  ["chow", "sunlamp", "clogs"],
  ["bite", "hazelnut", "glasses"],
  ["cleavage", "lieu", "briefs"],
  ["bloom", "beyond", "grit"],
  ["morphology", "booking", "chard"],
  ["strategy", "curio", "monopoly"],
  ["ice-cream", "patient", "dune"],
  ["chapter", "SUV", "lentil"],
  ["forgery", "puddle", "hay"],
  ["effective", "onion", "resolution"],
  ["drummer", "norm", "temper"],
  ["characterization", "spud", "methane"],
  ["ladle", "ring", "cabinet"],
  ["lace", "charm", "goodbye"],
  ["glory", "bedrock", "testament"],
  ["stance", "propane", "clip"],
  ["comportment", "lipid", "injustice"],
  ["cultivator", "air", "rod"],
  ["suck", "horizon", "formamide"],
  ["progression", "mochi", "silo"],
  ["schooner", "drapes", "spec"],
  ["appendix", "cursor", "division"],
  ["nudge", "nestmate", "sponge"],
  ["external", "rubbish", "foray"],
  ["ecumenist", "instruction", "pigpen"],
  ["roast", "sonnet", "innocence"],
  ["kit", "eyelid", "schnitzel"],
  ["grocery", "markup", "grief"],
  ["outside", "hare", "intestine"],
  ["patroller", "soccer", "calico"],
  ["boost", "garbage", "priesthood"],
  ["splendor", "deduction", "interviewer"],
  ["licorice", "sonar", "overview"],
  ["orient", "chopsticks", "adobe"],
  ["disposal", "razor", "homeownership"],
  ["politician", "paragraph", "sniffle"],
  ["havoc", "boat", "sled"],
  ["gingerbread", "cross-contamination", "codon"],
  ["howitzer", "skyline", "e-book"],
  ["soy", "chivalry", "beak"],
  ["bench", "precipitation", "stick"],
  ["astronomy", "discipline", "sister"],
  ["switching", "suppression", "tale"],
  ["creativity", "sultan", "barrel"],
  ["offering", "cenotaph", "divorce"],
  ["footstep", "sturgeon", "antechamber"],
  ["survey", "kindness", "dare"],
  ["sadness", "replacement", "polarization"],
  ["constellation", "province", "alpha"],
  ["nougat", "evaporation", "scrim"],
  ["analogy", "hydraulics", "abolishment"],
  ["e-mail", "dew", "carpeting"],
  ["poignance", "meteorology", "rice"],
  ["shelter", "kazoo", "hull"],
  ["landscape", "plate", "fencing"],
  ["fanlight", "kamikaze", "neighbourhood"],
  ["stockings", "average", "search"],
  ["blessing", "debate", "aftershock"],
  ["scheme", "accountability", "symbol"],
  ["quart", "ecology", "counselling"],
  ["conifer", "host", "nurse"],
  ["second", "insert", "radar"],
  ["thermometer", "illegal", "election"],
  ["thanks", "belt", "sail"],
  ["dump truck", "shirt", "input"],
  ["rationale", "plasterboard", "politics"],
  ["fillet", "ratepayer", "engine"],
  ["harvest", "appearance", "optimization"],
  ["stripe", "expression", "fen"],
  ["slippers", "congregation", "shortwave"],
  ["judge", "instant", "longboat"],
  ["surname", "everybody", "code"],
  ["painter", "step-son", "mesenchyme"],
  ["allegation", "passion", "strap"],
  ["channel", "strait", "pronoun"],
  ["breakpoint", "nexus", "skiing"],
  ["affect", "happiness", "local"],
  ["shore", "concern", "intuition"],
  ["oven", "lard", "makeover"],
  ["contract", "evaluator", "past"],
  ["achiever", "affair", "lunchmeat"],
  ["cracker", "tailor", "storm"],
  ["lode", "ptarmigan", "pink"],
  ["difference", "laryngitis", "lens"],
  ["mantle", "tanker", "declaration"],
  ["carport", "private", "colony"],
  ["swing", "pen", "statute"],
  ["glee", "acid", "ballet"],
  ["can", "swanling", "delay"],
  ["thrush", "clause", "teepee"],
  ["superiority", "editor", "telephone"],
  ["policeman", "hemisphere", "preserves"],
  ["corral", "short", "outlaw"],
  ["hash", "laboratory", "collateral"],
  ["drama", "ravioli", "fountain"],
  ["speakerphone", "ladybug", "doorpost"],
  ["gallon", "paper", "millimeter"],
  ["debris", "depression", "azimuth"],
  ["occupation", "posterior", "musculature"],
  ["diarist", "pancake", "penny"],
  ["shareholder", "gladiolus", "place"],
  ["selling", "fiery", "emery"],
  ["eligibility", "bouquet", "shearling"],
  ["latency", "perp", "profile"],
  ["solitaire", "reverse", "kitty"],
  ["purse", "flair", "administration"],
  ["auditorium", "shipper", "ellipse"],
  ["blue", "courthouse", "darn"],
  ["poll", "boutique", "calibre"],
  ["joke", "game", "servant"],
  ["proctor", "soul", "classic"],
  ["physics", "setback", "identity"],
  ["column", "cardigan", "diary"],
  ["mini-skirt", "birdhouse", "rhyme"],
  ["announcement", "inevitable", "antigen"],
  ["imbalance", "following", "cayenne"],
  ["platter", "clover", "grade"],
  ["caramel", "disarmament", "polliwog"],
  ["prostrate", "chuck", "sand"],
  ["candidacy", "beck", "seaplane"],
  ["sexuality", "archeology", "cabin"],
  ["rainy", "closet", "mob"],
  ["last", "allergist", "dog"],
  ["linguistics", "grasshopper", "curtain"],
  ["reboot", "summary", "scissors"],
  ["riser", "internet", "canal"],
  ["syrup", "planter", "expectancy"],
  ["likelihood", "herbs", "sneakers"],
  ["crayon", "storyboard", "jug"],
  ["deviance", "technician", "sill"],
  ["cello", "hydrolyze", "dulcimer"],
  ["counterterrorism", "attic", "sprout"],
  ["dud", "dairy", "fruit"],
  ["console", "butterfly", "feast"],
  ["footnote", "aggradation", "cluster"],
  ["anchovy", "samurai", "therapist"],
  ["customer", "restoration", "insect"],
  ["stamp", "podcast", "medium"],
  ["appetizer", "standardisation", "ecosystem"],
  ["procedure", "pain", "classification"],
  ["heaven", "snow", "lily"],
  ["nut", "dishwasher", "shovel"],
  ["anyone", "directive", "slave"],
  ["thrift", "incense", "banking"],
  ["pea", "hovercraft", "bird-watcher"],
  ["sphere", "ownership", "houseboat"],
  ["potential", "accord", "lyre"],
  ["mini", "immigration", "bother"],
  ["tachometer", "basil", "orchid"],
  ["sleepiness", "normalization", "jade"],
  ["rifle", "capitulation", "climb"],
  ["casserole", "pop", "door"],
  ["grey", "emergent", "lunchroom"],
  ["pyramid", "integrity", "bubble"],
  ["courtroom", "frontier", "million"],
  ["overcharge", "father-in-law", "policy"],
  ["sentiment", "ambulance", "dividend"],
  ["alcohol", "bangle", "creation"],
  ["employ", "sty", "opponent"],
  ["perfume", "interconnection", "longitude"],
  ["nightlife", "god", "limo"],
  ["cradle", "accident", "tenant"],
  ["screwdriver", "numeric", "correspondence"],
  ["abbey", "crop", "sofa"],
  ["sermon", "opportunist", "astrology"],
  ["pup", "jewel", "illiteracy"],
  ["seeder", "photoreceptor", "hundred"],
  ["refuge", "blackboard", "petitioner"],
  ["knock", "oxygen", "mathematics"],
  ["bower", "step-sister", "radio"],
  ["rug", "ale", "codling"],
  ["effect", "substitution", "claim"],
  ["knitting", "murder", "incarnation"],
  ["gliding", "prelude", "theater"],
  ["leverage", "subcomponent", "halloween"],
  ["spacing", "safe", "theology"],
  ["pineapple", "homogenate", "optimal"],
  ["solicitor", "piety", "fuck"],
  ["moonshine", "juggernaut", "opposite"],
  ["saviour", "pumpernickel", "brother-in-law"],
  ["railroad", "person", "mayonnaise"],
  ["participant", "stool", "bulb"],
  ["attorney", "epee", "stitcher"],
  ["hydrant", "marble", "frequency"],
  ["proximity", "muskrat", "pajamas"],
  ["midden", "cow", "tag"],
  ["event", "gastropod", "shame"],
  ["executive", "hobbit", "chronograph"],
  ["fender", "almanac", "feature"],
  ["chamber", "artifact", "clapboard"],
  ["army", "guidance", "fixture"],
  ["pickax", "attitude", "downgrade"],
  ["chemical", "extreme", "lantern"],
  ["doc", "fatigues", "safety"],
  ["scam", "overcoat", "grandpa"],
  ["elephant", "sustainment", "temperature"],
  ["speedboat", "soup", "semantics"],
  ["heart-throb", "dick", "sleeping"],
  ["sting", "operating", "saint"],
  ["sense", "case", "rainbow"],
  ["embryo", "caribou", "stomach"],
  ["assertion", "computer", "lightscreen"],
  ["caliber", "music", "moonlight"],
  ["ashtray", "colorlessness", "jump"],
  ["advancement", "pavement", "category"],
  ["pillar", "secretariat", "rowing"],
  ["cyclone", "hard-hat", "otter"],
  ["priority", "clasp", "accelerator"],
  ["dungeon", "teacher", "misrepresentation"],
  ["membrane", "legislature", "native"],
  ["connection", "infusion", "inquiry"],
  ["pillow", "shirtdress", "greatness"],
  ["news", "lady", "back-up"],
  ["fibrosis", "anesthesiology", "cube"],
  ["stylus", "oar", "thrill"],
  ["papaya", "suffocation", "group"],
  ["detective", "catalyst", "recording"],
  ["parchment", "thought", "soprano"],
  ["pug", "picturesque", "reality"],
  ["invader", "loan", "bag"],
  ["dinner", "investigator", "disengagement"],
  ["brush", "axis", "chalk"],
  ["dusk", "cymbal", "editing"],
  ["monsoon", "pioneer", "influence"],
  ["pliers", "mule", "handle"],
  ["info", "boyfriend", "briefing"],
  ["assumption", "decoration", "hostel"],
  ["icy", "surface", "pinecone"],
  ["bush", "aperitif", "persimmon"],
  ["dark", "end", "departure"],
  ["mouton", "process", "fraudster"],
  ["jealousy", "birdcage", "cheque"],
  ["grassland", "bondsman", "marathon"],
  ["kettle", "foundation", "balloonist"],
  ["cinema", "collector", "economy"],
  ["pheromone", "gather", "suet"],
  ["clamp", "heritage", "questionnaire"],
  ["helo", "collection", "road"],
  ["convertible", "judo", "passbook"],
  ["mattock", "examination", "saffron"],
  ["med", "residence", "chop"],
  ["ignorant", "sprinter", "high-rise"],
  ["clockwork", "subexpression", "espalier"],
  ["commuter", "fun", "pipe"],
  ["partner", "roar", "drug"],
  ["passenger", "bear", "custard"],
  ["soybean", "slaw", "bout"],
  ["sleep", "pulley", "feedback"],
  ["cheek", "kidney", "doctor"],
];
const request = `https://api.dictionaryapi.dev/api/v2/entries/en/`;
let readyForInput = true;

const days = () => {
  let date_1 = new Date("3/13/2023");
  let date_2 = new Date();
  let difference = date_2.getTime() - date_1.getTime();
  let TotalDays = Math.ceil(difference / (1000 * 3600 * 24)) - 1;
  return TotalDays;
};

localStorage.setItem("currentDate", new Date().toDateString());

function selectWord() {
  if (localStorage.getItem("wordNum") === null) {
    localStorage.setItem("wordNum", 0);
  } else if (localStorage.getItem("wordNum") === NaN) {
    localStorage.setItem("wordNum", 1);
  }
  let selectedWord = words[days()][parseInt(localStorage.getItem("wordNum"))];
  return selectedWord;
}

async function getDefinition(word) {
  const res = await axios.get(request + word);
  const definition = res.data[0]["meanings"][0]["definitions"][0]["definition"];
  showDefinition(definition);
}

function startGame() {
  if (checkIfCompleted()) {
    const selectedWord = selectWord();
    getDefinition(selectedWord);
    createLetterBoxes(selectedWord);
    letterBoxInputs(selectedWord);
    revealLetter(selectedWord);
  }
}

function checkIfCompleted() {
  if (localStorage.getItem("dayCompleted") != new Date().getDay()) {
    return true;
  }
  return false;
}

function showDefinition(definition) {
  const defh4 = document.querySelector("#definition");
  defh4.innerHTML = definition;
}

function createLetterBoxes(word) {
  const wordRow = document.querySelector("#wordRow");
  for (let letters of word) {
    const letterDiv = document.createElement("div");
    letterDiv.classList.add("letter-boxes");
    letterDiv.classList.add("animate__animated");
    wordRow.append(letterDiv);
  }
}

function letterBoxInputs(selectedWord) {
  const letterBoxes = document.querySelectorAll(".letter-boxes");
  let place = 0;
  const keys = document.querySelectorAll(".key");
  const enter = document.querySelector(".enter");
  const back = document.querySelector(".back");

  enter.addEventListener("click", () => {
    const guess = getGuess();
    if (
      selectedWord == guess &&
      !letterBoxes[0].classList.contains("guessedCorrectly") &&
      readyForInput
    ) {
      wordCompleted();
    } else if (!letterBoxes[0].classList.contains("guessedCorrectly")) {
      place = incorrectGuess();
    }
  });

  back.addEventListener("click", () => {
    if (
      place > 0 &&
      place <= letterBoxes.length &&
      !letterBoxes[place - 1].classList.contains("hintedLetter") &&
      !letterBoxes[place - 1].classList.contains("guessedCorrectly") &&
      readyForInput
    ) {
      --place;
      letterBoxes[place].classList.remove("animate__pulse");
      letterBoxes[place].innerHTML = "";
    }
  });

  for (let key of keys) {
    key.addEventListener("click", (e) => {
      if (place < letterBoxes.length) {
        while (
          letterBoxes[place].classList.contains("hintedLetter") &&
          place < letterBoxes.length - 1
        ) {
          ++place;
        }
      }

      if (
        place < letterBoxes.length &&
        !letterBoxes[place].classList.contains("hintedLetter") &&
        readyForInput
      ) {
        letterBoxes[place].classList.add("animate__pulse");
        letterBoxes[place].innerHTML = e.target.innerHTML;
        if (place < letterBoxes.length) {
          ++place;
        }
      }
    });
  }

  document.addEventListener("keyup", (e) => {
    if (place < letterBoxes.length) {
      while (
        letterBoxes[place].classList.contains("hintedLetter") &&
        place < letterBoxes.length - 1
      ) {
        ++place;
      }
    }
    if (
      e.keyCode >= "65" &&
      e.keyCode <= "90" &&
      place < letterBoxes.length &&
      !letterBoxes[place].classList.contains("hintedLetter") &&
      readyForInput
    ) {
      letterBoxes[place].classList.add("animate__pulse");
      letterBoxes[place].innerHTML = e.key.toUpperCase();
      if (place < letterBoxes.length) {
        ++place;
      }
    } else if (
      e.key === "Backspace" &&
      place > 0 &&
      place <= letterBoxes.length &&
      !letterBoxes[place - 1].classList.contains("hintedLetter") &&
      !letterBoxes[place - 1].classList.contains("guessedCorrectly") &&
      readyForInput
    ) {
      --place;
      letterBoxes[place].classList.remove("animate__pulse");
      letterBoxes[place].innerHTML = "";
    } else if (
      e.key === "Enter" &&
      !letterBoxes[place - 1].classList.contains("guessedCorrectly")
    ) {
      const guess = getGuess();
      if (selectedWord == guess) {
        wordCompleted();
      } else {
        place = incorrectGuess();
      }
    }
  });
}

function revealLetter(selectedWord) {
  let place = 0;
  const letterBoxes = document.querySelectorAll(".letter-boxes");
  const revealButton = document.querySelector(".reveal");
  revealButton.addEventListener("click", () => {
    if (
      place < selectedWord.length &&
      !letterBoxes[place].classList.contains("guessedCorrectly")
    ) {
      letterBoxes[place].innerHTML = selectedWord[place].toUpperCase();
      letterBoxes[place].classList.add("animate__flipInX");
      letterBoxes[place].classList.toggle("hintedLetter");
      ++place;
    }
  });
}

function getGuess() {
  const letterBoxes = document.querySelectorAll(".letter-boxes");
  let guess = "";
  for (let letter of letterBoxes) {
    guess = guess + letter.innerHTML;
  }
  return guess.toLowerCase();
}

function incorrectGuess() {
  readyForInput = false;
  const letterBoxes = document.querySelectorAll(".letter-boxes");
  let newPlace = 0;
  for (let letter of letterBoxes) {
    letter.classList.remove(
      "guessedIncorrectly",
      "animate__shakeX",
      "animate__flipInX",
      "animate__pulse"
    );
    letter.classList.add("guessedIncorrectly", "animate__shakeX");
  }
  setTimeout(() => {
    for (let letter of letterBoxes) {
      if (letter.classList.contains("hintedLetter")) {
        ++newPlace;
      } else {
        letter.innerHTML = "";
      }

      letter.classList.remove(
        "guessedIncorrectly",
        "animate__shakeX",
        "animate__flipInX",
        "animate__pulse"
      );
    }
    readyForInput = true;
  }, 500);
  incorrectScoreIncrement();
  return newPlace;
}

const share = document.querySelector(".share");
share.addEventListener("click", () => {
  navigator.share({
    text: `I scored a ${getTotalScore()} in today's Definy. Play at https://playdefiny.com`,
  });
});

function wordCompleted() {
  const letterBoxes = document.querySelectorAll(".letter-boxes");
  let wordNum = parseInt(localStorage.getItem("wordNum"));
  for (let letter of letterBoxes) {
    letter.classList.remove(
      "guessedIncorrectly",
      "animate__shakeX",
      "animate__flipInX",
      "animate__pulse"
    );
    letter.classList.add("guessedCorrectly", "animate__tada");
    if (letter.classList.contains("hintedLetter")) {
      revealedScoreIncrement();
    }
  }
  if (wordNum === 2) {
    let completedDate = new Date().toDateString();
    localStorage.setItem("completedDay", completedDate);
    localStorage.setItem("wordNum", 0);
    setTimeout(() => {
      showResults();
    }, 1000);
  } else {
    convertToNextWord();
    wordNum++;
    localStorage.setItem("wordNum", wordNum);
    document.addEventListener("keyup", (e) => {
      if (e.key === "Enter") {
        location.reload();
      }
    });
  }
}

function showResults() {
  updateStatsModal();
  $("#testModal").modal("show");
}

function incorrectScoreIncrement() {
  let incorScore = parseInt(
    localStorage.getItem(`incorScore${new Date().toDateString()}`)
  );
  ++incorScore;
  localStorage.setItem(`incorScore${new Date().toDateString()}`, incorScore);
}

function revealedScoreIncrement() {
  let revScore = parseInt(
    localStorage.getItem(`revScore${new Date().toDateString()}`)
  );
  ++revScore;
  localStorage.setItem(`revScore${new Date().toDateString()}`, revScore);
}

function getRevealedScore() {
  return localStorage.getItem(`revScore${new Date().toDateString()}`);
}

function getIncorrectScore() {
  return localStorage.getItem(`incorScore${new Date().toDateString()}`);
}

const getTotalScore = () => {
  return parseInt(getIncorrectScore()) + parseInt(getRevealedScore());
};

function updateStatsModal() {
  let stats = document.querySelector(".stats");
  stats.innerHTML = `You had <span style='color: red'><b>${getIncorrectScore()}</b></span> incorrect guesses and <span style='color: cyan;'><b>${getRevealedScore()}</b></span> revealed letters for a total score of: <span style='color: green'>${getTotalScore()} </span><br><br><br> There will be three new words tomorrow :)`;
}

function convertToNextWord() {
  const enterGuess = document.querySelector(".enter");
  enterGuess.innerHTML = "Next Word";
  enterGuess.addEventListener("click", () => {
    location.reload();
  });
}

if (localStorage.getItem(`revScore${new Date().toDateString()}`) === null) {
  localStorage.setItem(`revScore${new Date().toDateString()}`, 0);
}
if (localStorage.getItem(`incorScore${new Date().toDateString()}`) === null) {
  localStorage.setItem(`incorScore${new Date().toDateString()}`, 0);
}

if (
  localStorage.getItem("completedDay") != localStorage.getItem("currentDate")
) {
  startGame();
} else {
  showResults();
}
